eureka:
  client:
    serviceUrl:
      defaultZone: http://malson:123@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: yxp-sleuth-server
spring:
  application:
    name: yxp-sleuth-server
server:
  port: 9411