server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://malson:123@localhost:8761/eureka
    healthcheck:
      enabled: true
security:
  basic:
    enabled: true
  user:
    name: malson
    password: 123