eureka:
  client:
    serviceUrl:
      defaultZone: http://malson:123@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: yxp-config-server
spring:
  application:
    name: yxp-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/malsonForMLS/yxp-config.git
          username: malsonForMLS
          password: mm210640
server:
  port: 9000